version: "3"
services:
  anchorit:
    image: node:10
    container_name: anchorit
    depends_on:
      - connect
    working_dir: /home/node/app
    networks:
      - local_default
    command: bash -c 'yarn start'
    volumes:
      - ../anchorit:/home/node/app
    ports:
      - 3000:3000


networks:
  local_default:
